// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNVpeaFsDOre87ay6AOJxJofowvZ41V1s',
    appId: '1:526879244519:web:19da2540eea911d425e242',
    messagingSenderId: '526879244519',
    projectId: 'my-flutter-app-05',
    authDomain: 'my-flutter-app-05.firebaseapp.com',
    storageBucket: 'my-flutter-app-05.firebasestorage.app',
    measurementId: 'G-3VEBYWXV7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaJippI86RQrUUU0aDdqaA5bOrH691vU0',
    appId: '1:526879244519:android:8568eda8b023564e25e242',
    messagingSenderId: '526879244519',
    projectId: 'my-flutter-app-05',
    storageBucket: 'my-flutter-app-05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2s8BRtZVCO--gK1AGKktixMcOGUprKOc',
    appId: '1:526879244519:ios:7d285c7f3bef6f4325e242',
    messagingSenderId: '526879244519',
    projectId: 'my-flutter-app-05',
    storageBucket: 'my-flutter-app-05.firebasestorage.app',
    iosBundleId: 'com.example.app05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2s8BRtZVCO--gK1AGKktixMcOGUprKOc',
    appId: '1:526879244519:ios:7d285c7f3bef6f4325e242',
    messagingSenderId: '526879244519',
    projectId: 'my-flutter-app-05',
    storageBucket: 'my-flutter-app-05.firebasestorage.app',
    iosBundleId: 'com.example.app05',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNVpeaFsDOre87ay6AOJxJofowvZ41V1s',
    appId: '1:526879244519:web:645b35a7d651ea9925e242',
    messagingSenderId: '526879244519',
    projectId: 'my-flutter-app-05',
    authDomain: 'my-flutter-app-05.firebaseapp.com',
    storageBucket: 'my-flutter-app-05.firebasestorage.app',
    measurementId: 'G-BN1XBH222C',
  );
}
